softdep amlogic-pm pre: amlogic-clk amlogic-clk-soc-t7
softdep amlogic-dvb pre: amlogic-pm
softdep aml_media pre: amlogic-dvb
softdep amlogic-camera pre: amlogic-dvb
softdep amlogic-thermal pre: amlogic-pm
softdep amlogic-usb pre: amlogic-pm
softdep aml_drm pre: amlogic-pm
